
export const KafkaConsumerGroups = {

    CE_SUB_NORMAL_EXEC : 'CE_SUBMISSION_NORMAL_EXEC',
    CE_SUB_BATTLE_EXEC : 'CE_SUBMISSION_BATTLE_EXEC',

    CE_RUN_NORMAL_EXEC : 'CE_RUN_NORMAL_EXEC',
    CE_RUN_BATTLE_EXEC : 'CE_RUN_BATTLE_EXEC',

    CE_CUSTOM_NORMAL_EXEC : 'CE_CUSTOM_NORMAL_EXEC',

} as const